# Generated by Django 3.0.5 on 2020-04-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_website', models.TextField()),
                ('property_name', models.TextField()),
                ('street', models.TextField(default='')),
                ('region', models.TextField(default='')),
                ('postcode', models.TextField(default='')),
                ('price', models.FloatField()),
                ('including_utilies', models.BooleanField()),
                ('area', models.FloatField()),
                ('number_of_bedrooms', models.IntegerField()),
                ('state_of_furnishing', models.TextField()),
                ('available_from', models.DateTimeField()),
                ('offered_since', models.DateTimeField()),
                ('energy_label', models.TextField(null=True)),
                ('description_from_tenant', models.TextField()),
                ('tenant_contact_information', models.TextField(default='')),
                ('property_website_source', models.TextField(default='')),
                ('property_source_url', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('type_of_property', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homedashboard.Home')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('distance_item_name', models.TextField()),
                ('distance_in_meters', models.FloatField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homedashboard.Home')),
            ],
        ),
    ]
