# Generated by Django 3.0.5 on 2020-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedashboard', '0002_auto_20200429_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='year_of_construction',
            field=models.IntegerField(null=True),
        ),
    ]
