# Generated by Django 3.0.6 on 2020-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedashboard', '0004_auto_20200508_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='balcony_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='facilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='garage_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='garden_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='number_of_bathrooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='rental_period',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='home',
            name='storage_present',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
