# Generated by Django 3.0.6 on 2020-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedashboard', '0006_home_type_of_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='srcset',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
